Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
server: 127.0.0.1
port: 9097
database: highlands5
table: survey9b
users table: users99

Traceback (most recent call last):
  File "server.py", line 295, in <module>
    httpd.serve_forever()
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/socketserver.py", line 236, in serve_forever
    ready = selector.select(poll_interval)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
server: 127.0.0.1
port: 9097
database: highlands5
table: survey9b
users table: users99

Traceback (most recent call last):
  File "server.py", line 295, in <module>
    httpd.serve_forever()
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/socketserver.py", line 236, in serve_forever
    ready = selector.select(poll_interval)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
Traceback (most recent call last):
  File "server.py", line 23, in <module>
    from checkbox import Checkbox
  File "libs/checkbox.py", line 15, in <module>
    xl = Excel()
  File "libs/excel.py", line 120, in __init__
    self.options = self.extractOptions(table)
  File "libs/excel.py", line 34, in extractOptions
    df.drop(['Number', 'Important', 'Section', 'Question','Type'], axis = 1, inplace = True)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/core/generic.py", line 1907, in drop
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/seddon/Anaconda36/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py", line 3262, in drop
    labels[mask])
ValueError: labels ['Important'] not contained in axis
